# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  before_script:
    - sudo apt-get update && sudo apt-get install make automake libtool libtool-bin autoconf doxygen gfortran g++
    - ./non_interactive_autogen.sh -s

test:
  stage: test
  script:
    - make check -k -s
