image: ubuntu:18.04

stages:
- build-and-test

build-and-test:
  stage: build-and-test
  before_script:
    - apt-get update && apt-get -y install make automake libtool libtool-bin autoconf doxygen gfortran g++
  script:
    - ./non_interactive_autogen.sh -s
    - make check -k -s
