image: ubuntu:18.04

build:
  stage: build
  before_script:
    - apt-get update && apt-get install make automake libtool libtool-bin autoconf doxygen gfortran g++
  script:
    - ./non_interactive_autogen.sh -s

test:
  stage: test
  script:
    - make check -k -s
